### ISSUE TITLE
Remove Redis Import in Authorizer

### ISSUE THREAD

**Issue by ankitsultana** [GoogleCloudPlatform/gcp-token-broker#12]
I don't think the authorizer depends on redis, so we can remove this.

https://github.com/GoogleCloudPlatform/gcp-token-broker/blob/8a4d90d14debf7def7ce7c65bab9f8b76da23ae5/apps/authorizer/database.py#L18

**Comment by jphalip** [comment]
Sorry for the late response. The Authorizer app was rewritten from Python to Java, so this isn't relevant now. Thanks for the report though!
