### ISSUE TITLE
Read TLS Certificate from file

### ISSUE THREAD

**Issue by ankitsultana** [GoogleCloudPlatform/gcp-token-broker#18]
https://github.com/GoogleCloudPlatform/gcp-token-broker/blob/635aaf0d1357df409c289c536cfcf693a54eb385/connector/src/main/java/com/google/cloud/broker/hadoop/fs/BrokerGateway.java#L63

It seems the broker-connector is currently reading the tls-certificate of the broker directly from `core-site.xml`. Can we allow an option of loading the certificate from a file?

**Comment by jphalip** [comment]
Good idea. We could add a new setting `gcp.token.broker.tls.certificate.path`.

**Comment by ankitsultana** [comment]
@jphalip : Thoughts on this? If any change is required do let me know.

**Comment by jphalip** [comment]
Sorry for the delay. We've been busy making some large-ish code changes in the `next` branch. I'm hoping to merge and release these changes in the next week or two. After that it will be easier to merge this change. I'll keep you posted, thanks!

**Comment by ankitsultana** [comment]
Oh great. Thanks!

**Comment by jphalip** [comment]
This was just released in v0.5.0, thanks!
