### ISSUE TITLE
User-realm and broker-realm may not be the same

### ISSUE THREAD

**Issue by ankitsultana** [GoogleCloudPlatform/gcp-token-broker#20]
https://github.com/GoogleCloudPlatform/gcp-token-broker/blob/635aaf0d1357df409c289c536cfcf693a54eb385/connector/src/main/java/com/google/cloud/broker/hadoop/fs/BrokerGateway.java#L95

Here it seems that the realm of the logged-in user is being used to create the service principal of token-broker.

It might not be the case that both of them are part of the same realm, in which case this will fail.

**Comment by jphalip** [comment]
It's actually a requirement to create a broker principal in each realm, and then upload a separate keytab for each broker principal from each realm. It's expected that the user would create a SPNEGo token for the broker that's hosted in the same realm.

**Comment by ankitsultana** [comment]
Is there an issue with the broker and the user being in separate realms? There might be instances where one is running hadoop service-accounts in a different realm, and the users themselves in a different realm.

**Comment by jphalip** [comment]
The idea is that each realm *must* contain a "broker" principal, then upload a keytab for that principal to the broker service. This then enables the broker service to authenticate users from that realm.

**Comment by jphalip** [comment]
Sorry, I had missed that you had submitted a PR for this, and fixed it separately as part of c912677a82f93f1f3c84e4a1fbd2c12760e3da87

Please take a look and let me know that works.

**Comment by ankitsultana** [comment]
Yup. Looks good to me. Closing this since it is already fixed as part of your commit. Can you link that PR here in case someone needs to refer it later? I am not quite sure how to do that.
