### ISSUE TITLE
Add support for JDBC Database Backend

### ISSUE THREAD

**Issue by ankitsultana** [GoogleCloudPlatform/gcp-token-broker#3]
The current version of token-broker (both Java and Python) have support for Cloud Datastore. It'd be great to have token-broker support JDBC out of the box.

**Comment by jphalip** [comment]
Yes, this would be great. The backend would emit SQL queries for the get/save/delete methods. We also need to add an initialization step to create the table.

**Comment by jphalip** [comment]
This was added in 0.3.0.
