### ISSUE TITLE
Broker - KDC Firewall no longer required

### ISSUE THREAD

**Issue by ankitsultana** [GoogleCloudPlatform/gcp-token-broker#9]
IIUC, the Broker-KDC firewall setting is no longer required since KDC and Broker don't communicate in the new design. Can you confirm this?

https://github.com/GoogleCloudPlatform/gcp-token-broker/blob/281a0a2a121fe04ac830078ee8b12df22f3e9340/terraform/broker.tf#L43

**Comment by jphalip** [comment]
Yes, good catch, this should be removed.
